---
- name: Install packages on Ubuntu
  hosts: web_servers
  become: yes
  tasks:
  - name: Update package list
    apt: 
      update_cache: yes

  - name: Install required packages
    apt: 
      name:
        - realmd
        - adcli
        - sssd
        - libnss-sss
        - sssd-tools
        - samba-common-bin
        - oddjob
        - oddjob-mkhomedir
        - packagekit
        - haproxy
        - keepalived
      state: present
