---
- hosts: web_servers
  become: true
  tasks:
  -name: Install realmd 
  apt: name=realmd state=present update_cache=true
  - name: Install adcli
  apt: name=adcli state=present update_cache=true
  - name: Install sssd
  apt: name=sssd state=present update_cache=true
  -name: Install libnss-sss
  apt: name=libnss-sss state=present update_cache=true
  -name: install sssd-tools
  apt: name=sssd-tools state=present update_cache=true
  -name Install samba-common-bin
  apt: name=samba-common-bin state=present update_cache=true
  - name: Install oddjob
  apt: name=oddjob state=present update_cache=true
  - name: Install oddjob-mkhomedir
  apt: name=oddjob-mkhomedir state=present update_cache=true
  - name: Install packagekit
  apt: name=packagekit state=present update_cache=true
